image: node:10

cache:
    paths:
        - node_modules/
        - .yarn
# We tell GitLab to install all the packages
# before running anything.
# Docker images come with yarn preinstalled
before_script:
    ##
    ## Install ssh-agent if not already installed, it is required by Docker.
    ## (change apt-get to yum if you use an RPM-based image)
    ##
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    ##
    ## Run ssh-agent (inside the build environment)
    ##
    - eval $(ssh-agent -s)
    ##
    ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
    ## We're using tr to fix line endings which makes ed25519 keys work
    ## without extra base64 encoding.
    ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
    ##
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    ##
    ## Create the SSH directory and give it the right permissions
    ##
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    ##
    ##
    ## Assuming you created the SSH_KNOWN_HOSTS variable, uncomment the
    ## following two lines.
    ## - ssh-keyscan gitlab.awardwallet.com
    ##
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    ##
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - apt-get update -qq && apt-get install
    - rm -fr node_modules/
    - rm -fr .yarn
    - yarn cache clean
    - yarn config set cache-folder .yarn
    - yarn install --frozen-lockfile
stages:
    - lint
    - test
eslint:
    stage: lint
    script:
    #   -  git diff-index --name-only HEAD | grep -E "(.*)\.(jsx|js)$" | xargs yarn run test --quiet
        -  yarn eslint --quiet ./app/
test:
    stage: test
    script:
        -  yarn run test __tests__/
        -  yarn run test:android __tests__/
snyk:
    stage: test
    script:
        - sh ./scripts/snyk.sh
